<div class="owl-carousel owl-theme">
    <?php for($i = 1 ; $i<=3; $i++ ): ?>
    <div class="item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('carousel-'.$i.'')->toHtml(); ?>
    </div>
    <?php endfor; ?>
</div>
<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            $('.owl-carousel ').owlCarousel({
                loop:true,
                nav:false,
                items:1,
                dots:true,
                autoplay:true,
                autoplayTimeout:3000
            })
        });
    });
</script>
<button class="example-button-1 example-button-2" type="button"><span>Button</span></button>
